version: "3.8"

services:

  task-tracker:

    image: ${DOCKER_IMAGE}

    container_name: task-tracker

    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      PORT: 3000
